language: swift
osx_image: xcode9.4

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=ASN1Decoder.xcodeproj
  - IOS_FRAMEWORK_SCHEME="ASN1Decoder"
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6" SCHEME="$IOS_FRAMEWORK_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"

script:
  - set -o pipefail

  # Build Framework in Debug and Run Tests
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;

after_success:
  - bash <(curl -s https://codecov.io/bash)
